# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a9ba4a29e98e18c2a93a512e5884e1d3b55d6e595b4e8ff791a99e6bf19d092fc8b236ac0343739a094ce6d296f26b4a5bef2227bbb65ae2e5733200882090ef

test:
  secret_key_base: eff2b0d09aaa0d36bb0d9379f64c1e970b052d16cfb7a81aee9c3dccce631c4da487e09717247ba1c35a838653a48c06d06a37117bd2f590e5db41c28042d728

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
